export const Categories = [
    { _id: 1, name: "Shopping", icon: "shopping",Color: "#FF5733" },
    { _id: 2, name: "Playing", icon: "gamepad-variant",Color: "#33C3FF" },
    { _id: 3, name: "Rents", icon: "home-city",Color: "#FF33A1" },
    { _id: 4, name: "EMI", icon: "credit-card-outline",Color: "#33FF57" },
    { _id: 5, name: "Travel", icon: "airplane",Color: "#FFBD33" },
    { _id: 6, name: "Food", icon: "food",Color: "#FF33F6" },
    { _id: 7, name: "Bills", icon: "file-document",Color: "#33FFC5" },
    { _id: 8, name: "Health", icon: "hospital",Color: "#5733FF" },
    { _id: 9, name: "Entertainment", icon: "movie", Color: "#FFC300" },
    { _id: 10, name: "Groceries", icon: "cart-outline", Color: "#FF5733" },
    { _id: 11, name: "Utilities", icon: "lightbulb-outline", Color: "#33FF57" },
    { _id: 12, name: "Transportation", icon: "bus", Color: "#33C3FF" },
    { _id: 13, name: "Education", icon: "school", Color: "#FF33A1" },
    { _id: 14, name: "Insurance", icon: "shield-check-outline", Color: "#FF33F6" },
    { _id: 15, name: "Gifts & Donations", icon: "gift", Color: "#FFBD33" },
    { _id: 16, name: "Investments", icon: "chart-line", Color: "#33FFC5" },
    { _id: 17, name: "Subscriptions", icon: "card-text-outline", Color: "#5733FF" },
    { _id: 18, name: "Personal Care", icon: "spa", Color: "#FFC300" },
    { _id: 19, name: "Pets", icon: "dog", Color: "#33C3FF" },
    { _id: 20, name: "Dining Out", icon: "silverware-fork-knife", Color: "#FF5733" },
    { _id: 21, name: "Savings", icon: "bank-outline", Color: "#33FF57" },
    { _id: 22, name: "Clothing", icon: "tshirt-crew", Color: "#FF33A1" },
    { _id: 23, name: "Childcare", icon: "baby-carriage", Color: "#33FFBD" },
    { _id: 24, name: "Fitness", icon: "dumbbell", Color: "#FF5733" },
    { _id: 25, name: "Hobbies", icon: "palette", Color: "#FFBD33" },
    { _id: 26, name: "Home Improvement", icon: "home-modern", Color: "#FF33F6" },
    { _id: 27, name: "Alcohol & Bars", icon: "glass-cocktail", Color: "#5733FF" },
    { _id: 28, name: "Vacation", icon: "beach", Color: "#FFC300" },
    { _id: 29, name: "Phone", icon: "cellphone", Color: "#33C3FF" },
    { _id: 30, name: "Internet", icon: "wifi", Color: "#33FFC5" },
    { _id: 31, name: "Loan Payments", icon: "account-cash", Color: "#FF5733" },
    { _id: 32, name: "Household Supplies", icon: "broom", Color: "#FF33A1" },
    { _id: 33, name: "Beauty", icon: "lipstick", Color: "#FF33F6" },
    { _id: 34, name: "Parking", icon: "parking", Color: "#FFBD33" },
    { _id: 35, name: "Taxis & Rideshares", icon: "car", Color: "#33FF57" },
    { _id: 36, name: "Debt Repayment", icon: "bank-transfer-out", Color: "#FF5733" },
    { _id: 37, name: "Gadgets", icon: "tablet-cellphone", Color: "#5733FF" },
    { _id: 38, name: "Laundry", icon: "washing-machine", Color: "#33FFC5" },
    { _id: 39, name: "Rentals", icon: "car", Color: "#FF33F6" },
    { _id: 40, name: "Socializing", icon: "account-group", Color: "#33C3FF" },
    { _id: 41, name: "Car Maintenance", icon: "car-wrench", Color: "#FF33A1" },
    { _id: 42, name: "Housekeeping", icon: "home-outline", Color: "#FFC300" },
    { _id: 43, name: "Car Insurance", icon: "car", Color: "#33FF57" },
    { _id: 44, name: "Fuel", icon: "fuel", Color: "#33C3FF" },
    { _id: 45, name: "Public Transportation", icon: "train", Color: "#FF5733" },
    { _id: 46, name: "Event Tickets", icon: "ticket-outline", Color: "#FF33F6" },
    { _id: 47, name: "Bank Fees", icon: "bank-outline", Color: "#5733FF" },
    { _id: 48, name: "Charity", icon: "heart-outline", Color: "#FF33A1" },
    { _id: 49, name: "Wedding Expenses", icon: "ring", Color: "#FFBD33" },
    { _id: 50, name: "Photography", icon: "camera", Color: "#33FFC5" },
    { _id: 51, name: "Loans", icon: "account-cash", Color: "#33FF57" },
    { _id: 52, name: "Furniture", icon: "sofa-outline", Color: "#33C3FF" },
    { _id: 53, name: "Moving Expenses", icon: "truck", Color: "#FF5733" },
    { _id: 54, name: "Special Occasions", icon: "cake-variant", Color: "#FF33F6" }

  ];